name: PepOverlap
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - emboss=6.6.0
  - ipython=7.1.1
  - matplotlib=3.0.2
  - matplotlib-base=3.0.2
  - matplotlib-venn=0.11.5
  - pandas=0.23.4
  - pip=18.1
  - python=3.7.1
  - numpy=1.15.4
  - numpy-base=1.15.4
  - scipy=1.1.0
  - pip:
    - bash-kernel==0.7.1

