name: PepOverlap
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.81
  - bokeh=2.4.3
  - dill=0.3.6
  - emboss=6.6.0
  - holoviews=1.15.4
  - matplotlib=3.7.0
  - matplotlib-base=3.7.0
  - matplotlib-inline=0.1.6
  - matplotlib-venn=0.11.7
  - numpy=1.24.2
  - pandas=1.5.3
  - python=3.11.0
  - pyyaml=6.0
  - scipy=1.10.0
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - yaspin=2.2.0
